### ISSUE TITLE
TODO: Features

### ISSUE THREAD

**Issue by pi0neerpat** [pi0neerpat/sol-proxy#1]
- [ ] Get the list of import statements from the original file
- [ ] Flatten the file before getting all the pragma declarations, variables, structs
- [ ] Match items 
1. structs are only kept if they are used in a variable
2. imports are only kept if they are used in a struct or variable
- [ ] Find the highest pragma statement to use for Storage.sol and Structs.sol
- [ ] Check if Storage.sol, Structs.sol exists
- [ ] If they exist, then load the files and append the new variables, structs, import statements
- [ ] If the previous check found no Storage.sol, Structs.sol, then assume sol-proxy has not been run. Add the Proxiable.sol contract before the original contract. Add imports and inheritance to the original contract declarations for Storage.sol, Structs.sol, and Proxiable contracts.
